export function buildReadme({ user, topRepos }) {
  return `
# ${user.name || "GitHub Developer"}

${user.bio || ""}

## 📊 GitHub Stats
- Followers: ${user.followers}
- Following: ${user.following}

## ⭐ Top Repositories
${topRepos
  .map(
    r => `- [${r.name}](${r.url}) ⭐ ${r.stars} (${r.language || "N/A"})`
  )
  .join("\n")}

---
Generated by GitHub README Generator
`;
}
